/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import AccesoDatos.AccesoDatos;
import Entidades.Empresa;
import LogicaDeNegocio.LogicaSistema;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author esteban
 */
public class AgregarInfoEmpresa extends javax.swing.JFrame {

    public LogicaSistema objLogicaSistema;
    public AccesoDatos objAccesoDatos;

    /**
     * Creates new form AgregarInfoEmpresa
     */
    public AgregarInfoEmpresa() {
        initComponents(); // Inicializa todos los componentes de la interfaz gráfica
        this.setLocationRelativeTo(null);

        
        Empresa objEmpresa = new Empresa();
        AccesoDatos objAccessoDatos = new AccesoDatos();
        try {
            objAccessoDatos.leerArchivoDatosEmpresa(objEmpresa);
        } catch (IOException ex) {
            System.out.println(ex);;
        }

        cargarDatosTxt(objEmpresa); // Llama a cargarDatosTxt después de leer el archivo

        try {
            this.objLogicaSistema = new LogicaSistema();
        } catch (IOException ex) {
            ex.printStackTrace(); // Muestra el error en la consola
        }
    }

    private void cargarDatosTxt(Empresa objEmpresa) {

        txtNombreEmpresa.setText(objEmpresa.getNombreEmpresa());
        txtCedulaJuridica.setText(objEmpresa.getCedulaJuridica());
        txtNumeroTelefonico.setText(objEmpresa.getNumeroTelefonico());
        txtCorreoElectronico.setText(objEmpresa.getCorreoElectronico());
        txtNombrePatrono.setText(objEmpresa.getNombrePatrono());
        txtPrimerApellido.setText(objEmpresa.getPrimerApePatrono());
        txtSegundoApellido.setText(objEmpresa.getSegundoApePatrono());
        txtUbicacion.setText(objEmpresa.getUbicacion());

    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnGeneral = new javax.swing.JPanel();
        pnCentral = new javax.swing.JPanel();
        lblNombreEmpresa = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        lblCedulaJuridica = new javax.swing.JLabel();
        txtCedulaJuridica = new javax.swing.JTextField();
        lblNumeroTelefonico = new javax.swing.JLabel();
        txtNumeroTelefonico = new javax.swing.JTextField();
        lblCorreoElectronico = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        lblNombrePatrono = new javax.swing.JLabel();
        txtNombrePatrono = new javax.swing.JTextField();
        lblPrimerApellido = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        lblSegundoApellido = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        lblUbicacion = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        pnLaterarIzquierdo = new javax.swing.JPanel();
        pnSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        pnGeneral.setBackground(new java.awt.Color(153, 153, 153));
        pnGeneral.setLayout(null);

        pnCentral.setBackground(new java.awt.Color(242, 240, 235));
        pnCentral.setPreferredSize(new java.awt.Dimension(1070, 800));

        lblNombreEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreEmpresa.setText("Nombre de la empresa");

        txtNombreEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreEmpresa.setForeground(new java.awt.Color(0, 0, 0));

        lblCedulaJuridica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCedulaJuridica.setForeground(new java.awt.Color(0, 0, 0));
        lblCedulaJuridica.setText("Cedula jurídica");

        txtCedulaJuridica.setBackground(new java.awt.Color(255, 255, 255));
        txtCedulaJuridica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedulaJuridica.setForeground(new java.awt.Color(0, 0, 0));

        lblNumeroTelefonico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumeroTelefonico.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroTelefonico.setText("Numero telefónico");

        txtNumeroTelefonico.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroTelefonico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumeroTelefonico.setForeground(new java.awt.Color(0, 0, 0));

        lblCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoElectronico.setText("Correo electrónico");

        txtCorreoElectronico.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));

        lblNombrePatrono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombrePatrono.setForeground(new java.awt.Color(0, 0, 0));
        lblNombrePatrono.setText("Nombre del patrono");

        txtNombrePatrono.setBackground(new java.awt.Color(255, 255, 255));
        txtNombrePatrono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombrePatrono.setForeground(new java.awt.Color(0, 0, 0));

        lblPrimerApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrimerApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblPrimerApellido.setText("Primer apellido del patrono");

        txtPrimerApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtPrimerApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrimerApellido.setForeground(new java.awt.Color(0, 0, 0));

        lblSegundoApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSegundoApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblSegundoApellido.setText("Segundo apellido del patrono");

        txtSegundoApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtSegundoApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSegundoApellido.setForeground(new java.awt.Color(0, 0, 0));

        lblUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        lblUbicacion.setText("Ubicación");

        txtUbicacion.setBackground(new java.awt.Color(255, 255, 255));
        txtUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUbicacion.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 102));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar información");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCentralLayout = new javax.swing.GroupLayout(pnCentral);
        pnCentral.setLayout(pnCentralLayout);
        pnCentralLayout.setHorizontalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCentralLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEmpresa)
                    .addComponent(lblNumeroTelefonico)
                    .addComponent(lblCorreoElectronico)
                    .addComponent(lblNombrePatrono)
                    .addComponent(lblPrimerApellido)
                    .addComponent(lblUbicacion)
                    .addComponent(lblSegundoApellido)
                    .addComponent(lblCedulaJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreEmpresa)
                    .addComponent(txtCedulaJuridica)
                    .addComponent(txtNumeroTelefonico, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreoElectronico)
                    .addComponent(txtNombrePatrono)
                    .addComponent(txtPrimerApellido)
                    .addComponent(txtSegundoApellido)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
            .addGroup(pnCentralLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCentralLayout.setVerticalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCentralLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreEmpresa))
                .addGap(30, 30, 30)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaJuridica)
                    .addComponent(txtCedulaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroTelefonico))
                .addGap(30, 30, 30)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoElectronico)
                    .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePatrono)
                    .addComponent(txtNombrePatrono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerApellido)
                    .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegundoApellido))
                .addGap(30, 30, 30)
                .addGroup(pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUbicacion)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pnGeneral.add(pnCentral);
        pnCentral.setBounds(130, 130, 870, 570);

        pnLaterarIzquierdo.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout pnLaterarIzquierdoLayout = new javax.swing.GroupLayout(pnLaterarIzquierdo);
        pnLaterarIzquierdo.setLayout(pnLaterarIzquierdoLayout);
        pnLaterarIzquierdoLayout.setHorizontalGroup(
            pnLaterarIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnLaterarIzquierdoLayout.setVerticalGroup(
            pnLaterarIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pnGeneral.add(pnLaterarIzquierdo);
        pnLaterarIzquierdo.setBounds(0, 0, 130, 700);

        pnSuperior.setBackground(new java.awt.Color(0, 102, 102));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Edite la información de su empresa");

        javax.swing.GroupLayout pnSuperiorLayout = new javax.swing.GroupLayout(pnSuperior);
        pnSuperior.setLayout(pnSuperiorLayout);
        pnSuperiorLayout.setHorizontalGroup(
            pnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuperiorLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblTitulo)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnSuperiorLayout.setVerticalGroup(
            pnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuperiorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitulo)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pnGeneral.add(pnSuperior);
        pnSuperior.setBounds(130, 0, 870, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Empresa objEmpresa = new Empresa();
        objEmpresa.setNombreEmpresa(txtNombreEmpresa.getText());
        objEmpresa.setCedulaJuridica(txtCedulaJuridica.getText());
        objEmpresa.setNumeroTelefonico(txtNumeroTelefonico.getText());
        objEmpresa.setCorreoElectronico(txtCorreoElectronico.getText());
        objEmpresa.setNombrePatrono(txtNombrePatrono.getText());
        objEmpresa.setPrimerApePatrono(txtPrimerApellido.getText());
        objEmpresa.setSegundoApePatrono(txtSegundoApellido.getText());
        objEmpresa.setUbicacion(txtUbicacion.getText());

        if (txtNombreEmpresa.getText().isEmpty() || txtNombreEmpresa.getText().isBlank()
                || txtCedulaJuridica.getText().isEmpty() || txtCedulaJuridica.getText().isBlank()
                || txtNumeroTelefonico.getText().isEmpty() || txtNumeroTelefonico.getText().isBlank()
                || txtCorreoElectronico.getText().isEmpty() || txtCorreoElectronico.getText().isBlank()
                || txtNombrePatrono.getText().isEmpty() || txtNombrePatrono.getText().isBlank()
                || txtPrimerApellido.getText().isEmpty() || txtPrimerApellido.getText().isBlank()
                || txtSegundoApellido.getText().isEmpty() || txtSegundoApellido.getText().isBlank()
                || txtUbicacion.getText().isEmpty() || txtUbicacion.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                objLogicaSistema.guardarInformacionEmpresa(objEmpresa);

                JOptionPane.showMessageDialog(null, "Cambios guardados exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException err) {
                JOptionPane.showMessageDialog(null, "Error: " + err.getMessage());
            }

            this.hide();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarInfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarInfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarInfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarInfoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarInfoEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblCedulaJuridica;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblNombrePatrono;
    private javax.swing.JLabel lblNumeroTelefonico;
    private javax.swing.JLabel lblPrimerApellido;
    private javax.swing.JLabel lblSegundoApellido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JPanel pnCentral;
    private javax.swing.JPanel pnGeneral;
    private javax.swing.JPanel pnLaterarIzquierdo;
    private javax.swing.JPanel pnSuperior;
    private javax.swing.JTextField txtCedulaJuridica;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtNombrePatrono;
    private javax.swing.JTextField txtNumeroTelefonico;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
