/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import AccesoDatos.AccesoDatos;
import AccesoDatos.CorreoElectronicoNominas;
import AccesoDatos.CorreoElectronicoPatronal;
import AccesoDatos.CrearArchivoEmpleado;
import AccesoDatos.CrearArchivoPatrono;
import Entidades.Datos;
import Entidades.Empleado;
import Entidades.Empresa;
import LogicaDeNegocio.LogicaSistema;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ryzon
 */
public class GestionEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form GestionEmpleado
     */
    public static GestionEmpleado instancia;
    private Datos objDatos = new Datos();

    public GestionEmpleado() {

        try {
            this.objLogicaSistema = new LogicaSistema();
        } catch (IOException err) {

        }

        instancia = this;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTablaEmpleado();
    }

    public static GestionEmpleado getInstancia() {
        return instancia;
    }

    public LogicaSistema objLogicaSistema;

    private void limpiarCampos() {
        lblId.setText("");
        txtNombre.setText("");
        txtPrimerApellido.setText("");
        txtSegundoApellido.setText("");
        txtDireccion.setText("");
        txtCorreoElectronico.setText("");
        txtPuesto.setText("");
        txtSalarioBase.setText("");
        txtCedula.setText("");
    }

    public void cargarTablaEmpleado() {
        DefaultTableModel tablaEmpleados = new DefaultTableModel();

        tblEmpleados.setModel(tablaEmpleados);
        tablaEmpleados.addColumn("Id");
        tablaEmpleados.addColumn("Nombre");
        tablaEmpleados.addColumn("Primer Apellido");
        tablaEmpleados.addColumn("Segundo Apellido");
        tablaEmpleados.addColumn("Correo Electrónico");
        tablaEmpleados.addColumn("Cedula");
        tablaEmpleados.addColumn("Puesto");
        tablaEmpleados.addColumn("Salario base");
        tablaEmpleados.addColumn("Dirección");

        Empleado objEmpleado = new Empleado();

        try {
            objLogicaSistema.listarEmpleados(objEmpleado);
        } catch (IOException err) {
            JOptionPane.showMessageDialog(null, "Error: " + err);
        }

        for (String[] row : objEmpleado.getListaEmpleados()) {

            tablaEmpleados.addRow(row);

        }
        tblEmpleados.setModel(tablaEmpleados);

    }

    public void actualizarTablaEmpleados() {
        // Limpiar la tabla antes de volver a cargar los datos
        DefaultTableModel model = (DefaultTableModel) tblEmpleados.getModel();
        model.setRowCount(0);

        cargarTablaEmpleado(); // Volver a cargar los datos
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnGeneral = new javax.swing.JPanel();
        pnLaterarIzquierdo = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnEditarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        btnAnnadirInfoEmpresa = new javax.swing.JButton();
        btnReportePatronal = new javax.swing.JButton();
        btnNominas = new javax.swing.JButton();
        pnLateralDerecho = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrimerApellido = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        lblSegundoApellido = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        lblCorreoElectronico = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblPuesto = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        lblSalarioBase = new javax.swing.JLabel();
        txtSalarioBase = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTituloId = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnGeneral.setBackground(new java.awt.Color(153, 153, 153));
        pnGeneral.setLayout(null);

        pnLaterarIzquierdo.setBackground(new java.awt.Color(0, 102, 102));
        pnLaterarIzquierdo.setPreferredSize(new java.awt.Dimension(230, 800));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/LOGO ESQUINAS 3.png"))); // NOI18N

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAgregarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAgregarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarEmpleado.setText("Agregar nuevo empleado");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });

        btnEditarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEditarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarEmpleado.setText("Editar empleado");
        btnEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEmpleadoActionPerformed(evt);
            }
        });

        btnEliminarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEliminarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarEmpleado.setText("Eliminar empleado");
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });

        btnAnnadirInfoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        btnAnnadirInfoEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAnnadirInfoEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        btnAnnadirInfoEmpresa.setText("Ver información empresa");
        btnAnnadirInfoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnadirInfoEmpresaActionPerformed(evt);
            }
        });

        btnReportePatronal.setBackground(new java.awt.Color(255, 255, 255));
        btnReportePatronal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnReportePatronal.setForeground(new java.awt.Color(0, 0, 0));
        btnReportePatronal.setText("Enviar reporte patronal");
        btnReportePatronal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePatronalActionPerformed(evt);
            }
        });

        btnNominas.setBackground(new java.awt.Color(255, 255, 255));
        btnNominas.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnNominas.setForeground(new java.awt.Color(0, 0, 0));
        btnNominas.setText("Enviar nóminas");
        btnNominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNominasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLaterarIzquierdoLayout = new javax.swing.GroupLayout(pnLaterarIzquierdo);
        pnLaterarIzquierdo.setLayout(pnLaterarIzquierdoLayout);
        pnLaterarIzquierdoLayout.setHorizontalGroup(
            pnLaterarIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLaterarIzquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(btnEditarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAnnadirInfoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportePatronal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNominas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnLaterarIzquierdoLayout.setVerticalGroup(
            pnLaterarIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLaterarIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAnnadirInfoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnNominas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnReportePatronal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pnGeneral.add(pnLaterarIzquierdo);
        pnLaterarIzquierdo.setBounds(0, 0, 230, 800);

        pnLateralDerecho.setBackground(new java.awt.Color(242, 240, 235));
        pnLateralDerecho.setPreferredSize(new java.awt.Dimension(1070, 800));

        tblEmpleados.setBackground(new java.awt.Color(0, 102, 102));
        tblEmpleados.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tblEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));

        lblPrimerApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrimerApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblPrimerApellido.setText("Primer Apellido");

        txtPrimerApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtPrimerApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrimerApellido.setForeground(new java.awt.Color(0, 0, 0));

        lblSegundoApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSegundoApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblSegundoApellido.setText("Segundo Apellido");

        txtSegundoApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtSegundoApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSegundoApellido.setForeground(new java.awt.Color(0, 0, 0));

        lblCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoElectronico.setText("Correo Electrónico");

        txtCorreoElectronico.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));

        lblCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula.setText("Cédula");

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));

        lblPuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPuesto.setForeground(new java.awt.Color(0, 0, 0));
        lblPuesto.setText("Puesto");

        txtPuesto.setBackground(new java.awt.Color(255, 255, 255));
        txtPuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPuesto.setForeground(new java.awt.Color(0, 0, 0));

        lblSalarioBase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalarioBase.setForeground(new java.awt.Color(0, 0, 0));
        lblSalarioBase.setText("Salario base");

        txtSalarioBase.setBackground(new java.awt.Color(255, 255, 255));
        txtSalarioBase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSalarioBase.setForeground(new java.awt.Color(0, 0, 0));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccion.setText("Dirección");

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));

        lblTituloId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTituloId.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloId.setText("ID:");

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnLateralDerechoLayout = new javax.swing.GroupLayout(pnLateralDerecho);
        pnLateralDerecho.setLayout(pnLateralDerechoLayout);
        pnLateralDerechoLayout.setHorizontalGroup(
            pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLateralDerechoLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnLateralDerechoLayout.createSequentialGroup()
                        .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblPrimerApellido)
                            .addComponent(lblSegundoApellido)
                            .addComponent(lblCorreoElectronico)
                            .addGroup(pnLateralDerechoLayout.createSequentialGroup()
                                .addComponent(lblTituloId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblId)))
                        .addGap(18, 18, 18)
                        .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtPrimerApellido)
                            .addComponent(txtSegundoApellido)
                            .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125)
                        .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnLateralDerechoLayout.createSequentialGroup()
                                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCedula)
                                    .addComponent(lblPuesto))
                                .addGap(53, 53, 53)
                                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPuesto)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnLateralDerechoLayout.createSequentialGroup()
                                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSalarioBase)
                                    .addComponent(lblDireccion))
                                .addGap(18, 18, 18)
                                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        pnLateralDerechoLayout.setVerticalGroup(
            pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLateralDerechoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblTituloId))
                .addGap(18, 18, 18)
                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerApellido)
                    .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuesto)
                    .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoApellido)
                    .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalarioBase)
                    .addComponent(txtSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnLateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoElectronico)
                    .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pnGeneral.add(pnLateralDerecho);
        pnLateralDerecho.setBounds(230, 0, 1070, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed

        AgregarEmpleado frmAgregarEmpleado = new AgregarEmpleado();
        frmAgregarEmpleado.show();
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnAnnadirInfoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnadirInfoEmpresaActionPerformed
        // TODO add your handling code here:
        AgregarInfoEmpresa frmAgregarInfoEmpresa = new AgregarInfoEmpresa();
        frmAgregarInfoEmpresa.show();
    }//GEN-LAST:event_btnAnnadirInfoEmpresaActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
        CargarDatosTxt();
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmpleadoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblEmpleados.getSelectedRow();

        if (filaSeleccionada != -1) {

            if (txtNombre.getText().isEmpty() || txtNombre.getText().isBlank()
                    || txtPrimerApellido.getText().isEmpty() || txtPrimerApellido.getText().isBlank()
                    || txtSegundoApellido.getText().isEmpty() || txtSegundoApellido.getText().isBlank()
                    || txtCorreoElectronico.getText().isEmpty() || txtCorreoElectronico.getText().isBlank()
                    || txtCedula.getText().isEmpty() || txtCedula.getText().isBlank()
                    || txtPuesto.getText().isEmpty() || txtPuesto.getText().isBlank()
                    || txtSalarioBase.getText().isEmpty() || txtSalarioBase.getText().isBlank()
                    || txtDireccion.getText().isEmpty() || txtDireccion.getText().isBlank()) {

                JOptionPane.showMessageDialog(null, "No puede dejar campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    double salarioBase = Double.parseDouble(txtSalarioBase.getText());

                    Empleado objEmpleado = new Empleado();
                    objEmpleado.setId(Integer.parseInt(tblEmpleados.getValueAt(filaSeleccionada, 0).toString()));
                    objEmpleado.setNombre(txtNombre.getText());
                    objEmpleado.setPrimerApellido(txtPrimerApellido.getText());
                    objEmpleado.setSegundoApellido(txtSegundoApellido.getText());
                    objEmpleado.setCorreoElectronico(txtCorreoElectronico.getText());
                    objEmpleado.setCedula(txtCedula.getText());
                    objEmpleado.setPuesto(txtPuesto.getText());
                    objEmpleado.setDireccion(txtDireccion.getText());
                    objEmpleado.setSalarioBase(salarioBase);

                    objLogicaSistema.editarEmpleado(objEmpleado);

                    cargarTablaEmpleado();
                    JOptionPane.showMessageDialog(null, "Empleado editado correctamente.");
                    limpiarCampos();

                } catch (NumberFormatException e) {
                    // Manejar el error si el texto no se puede convertir a un número
                    JOptionPane.showMessageDialog(null, "El salario base ingresado no es un número válido.");
                } catch (IOException err) {
                    JOptionPane.showMessageDialog(null, "Error: " + err.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un empleado para editar.");
        }
    }//GEN-LAST:event_btnEditarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        // TODO add your handling code here:

        //Para revisar
        int filaSeleccionada = tblEmpleados.getSelectedRow();
        if (filaSeleccionada != -1) {

            String id = tblEmpleados.getValueAt(filaSeleccionada, 0).toString();
            Empleado objEmpleado = new Empleado();
            objEmpleado.setId(Integer.parseInt(id));

            try {
                objLogicaSistema.eliminarEmpleado(objEmpleado);
                JOptionPane.showMessageDialog(null, "Usuario Eliminado");
                cargarTablaEmpleado();
                limpiarCampos();
            } catch (IOException err) {
                JOptionPane.showMessageDialog(null, "Error: " + err.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un empleado para eliminarlo.");
        }

        actualizarTablaEmpleados();

    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnNominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNominasActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i < tblEmpleados.getRowCount(); i++) {
            String nombre = tblEmpleados.getValueAt(i, 1).toString(); // Columna del nombre
            String primerApellido = tblEmpleados.getValueAt(i, 2).toString(); // Columna del primerApellido
            String segundoApellido = tblEmpleados.getValueAt(i, 3).toString(); //Columna del segundoApellido
            String correo = tblEmpleados.getValueAt(i, 4).toString(); // Columna del correo
            double salarioBase = Double.parseDouble(tblEmpleados.getValueAt(i, 7).toString()); // Columna del salario base

            String asunto = "Nómina de Pago";
            String mensaje = "Hola " + nombre + ",\n\nAdjunto encontrarás tu nómina de pago.";

            // Crear objeto Datos con la información del empleado
            Datos objDatos = new Datos(correo, nombre, asunto, mensaje, salarioBase, primerApellido, segundoApellido);

            // Generar el PDF personalizado
            CrearArchivoEmpleado objCrearArchivo = new CrearArchivoEmpleado(objDatos);
            objCrearArchivo.crearPdf();

            // Enviar el correo con el PDF adjunto
            CorreoElectronicoNominas objEnvioCorreo = new CorreoElectronicoNominas(objDatos);
            Thread correoHilo = new Thread(objEnvioCorreo);
            correoHilo.start();
        }

        JOptionPane.showMessageDialog(null, "Correos con nóminas enviados correctamente.");

    }//GEN-LAST:event_btnNominasActionPerformed

    private void btnReportePatronalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePatronalActionPerformed
        // TODO add your handling code here:
        // Leer los datos del archivo de texto
        Empresa objEmpresa = new Empresa();
        AccesoDatos objAccessoDatos = new AccesoDatos();
        try {
            objAccessoDatos.leerArchivoDatosEmpresa(objEmpresa);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        // Configurar los datos del correo
        String correo = objEmpresa.getCorreoElectronico();
        String nombrePatrono = objEmpresa.getNombrePatrono();
        String primerApellido = objEmpresa.getPrimerApePatrono();
        String segundoApellido = objEmpresa.getSegundoApePatrono();
        String nombreEmpresa = objEmpresa.getNombreEmpresa();
        String cedulaJuridica = objEmpresa.getCedulaJuridica();
        String ubicacion = objEmpresa.getUbicacion();
        String numeroTelefonico = objEmpresa.getNumeroTelefonico();
        String asunto = "Reporte Patronal de " + objEmpresa.getNombreEmpresa();
        String mensaje = "Estimado/a " + nombrePatrono + ",\n\nAdjunto encontrará el reporte patronal solicitado.\n\nSaludos cordiales.";

        // Crear objeto Empresa con la información de la empresa
        objEmpresa = new Empresa(correo, nombrePatrono, primerApellido, segundoApellido, asunto, mensaje, nombreEmpresa, ubicacion, cedulaJuridica, numeroTelefonico);

        // Crear el archivo PDF del reporte patronal
        CrearArchivoPatrono creadorArchivo = new CrearArchivoPatrono(objEmpresa);
        creadorArchivo.crearPdf();

        // Enviar el correo con el PDF adjunto
        CorreoElectronicoPatronal objEnvioCorreo = new CorreoElectronicoPatronal(objEmpresa);
        Thread correoHilo = new Thread(objEnvioCorreo);
        correoHilo.start();

        JOptionPane.showMessageDialog(null, "Correo con el reporte patronal enviado correctamente.");

    }//GEN-LAST:event_btnReportePatronalActionPerformed

    private void CargarDatosTxt() {

        int filaSeleccionada = tblEmpleados.getSelectedRow();

        String id = tblEmpleados.getValueAt(filaSeleccionada, 0).toString();
        String nombre = tblEmpleados.getValueAt(filaSeleccionada, 1).toString();
        String primerApellido = tblEmpleados.getValueAt(filaSeleccionada, 2).toString();
        String segundoApellido = tblEmpleados.getValueAt(filaSeleccionada, 3).toString();
        String correoElectronico = tblEmpleados.getValueAt(filaSeleccionada, 4).toString();
        String cedula = tblEmpleados.getValueAt(filaSeleccionada, 5).toString();
        String puesto = tblEmpleados.getValueAt(filaSeleccionada, 6).toString();
        String salarioBase = tblEmpleados.getValueAt(filaSeleccionada, 7).toString();
        String direccion = tblEmpleados.getValueAt(filaSeleccionada, 8).toString();

        // Asignar los valores a los JTextField correspondientes
        lblId.setText(id);
        txtNombre.setText(nombre);
        txtPrimerApellido.setText(primerApellido);
        txtSegundoApellido.setText(segundoApellido);
        txtCorreoElectronico.setText(correoElectronico);
        txtCedula.setText(cedula);
        txtPuesto.setText(puesto);
        txtSalarioBase.setText(salarioBase);
        txtDireccion.setText(direccion);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnAnnadirInfoEmpresa;
    private javax.swing.JButton btnEditarEmpleado;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnNominas;
    private javax.swing.JButton btnReportePatronal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrimerApellido;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblSalarioBase;
    private javax.swing.JLabel lblSegundoApellido;
    private javax.swing.JLabel lblTituloId;
    private javax.swing.JPanel pnGeneral;
    private javax.swing.JPanel pnLateralDerecho;
    private javax.swing.JPanel pnLaterarIzquierdo;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtSalarioBase;
    private javax.swing.JTextField txtSegundoApellido;
    // End of variables declaration//GEN-END:variables
}
