/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Ryzon
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnGeneral = new javax.swing.JPanel();
        pnLateralColorIzquierdo = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblNombreEmpresa = new javax.swing.JLabel();
        lblDeveloper = new javax.swing.JLabel();
        pnLateralColorDerecho = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenna = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasenna = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(900, 610));

        pnGeneral.setBackground(new java.awt.Color(153, 153, 153));
        pnGeneral.setMinimumSize(new java.awt.Dimension(100, 100));
        pnGeneral.setPreferredSize(new java.awt.Dimension(900, 610));
        pnGeneral.setLayout(null);

        pnLateralColorIzquierdo.setBackground(new java.awt.Color(0, 102, 102));
        pnLateralColorIzquierdo.setPreferredSize(new java.awt.Dimension(450, 600));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/LOGO PROYECTO.png"))); // NOI18N

        lblNombreEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblNombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreEmpresa.setText("JESJ Company S.A.");

        lblDeveloper.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblDeveloper.setForeground(new java.awt.Color(153, 153, 153));
        lblDeveloper.setText("Developed by JESJ.");

        javax.swing.GroupLayout pnLateralColorIzquierdoLayout = new javax.swing.GroupLayout(pnLateralColorIzquierdo);
        pnLateralColorIzquierdo.setLayout(pnLateralColorIzquierdoLayout);
        pnLateralColorIzquierdoLayout.setHorizontalGroup(
            pnLateralColorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLateralColorIzquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(pnLateralColorIzquierdoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnLateralColorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeveloper)
                    .addComponent(lblNombreEmpresa))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnLateralColorIzquierdoLayout.setVerticalGroup(
            pnLateralColorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLateralColorIzquierdoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(lblDeveloper)
                .addGap(88, 88, 88))
        );

        pnGeneral.add(pnLateralColorIzquierdo);
        pnLateralColorIzquierdo.setBounds(0, 0, 450, 610);
        pnLateralColorIzquierdo.getAccessibleContext().setAccessibleName("");

        pnLateralColorDerecho.setBackground(new java.awt.Color(255, 255, 255));
        pnLateralColorDerecho.setPreferredSize(new java.awt.Dimension(450, 600));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Inicio de Sesión");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuario");

        lblContrasenna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContrasenna.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasenna.setText("Contraseña");

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));

        txtContrasenna.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasenna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContrasenna.setForeground(new java.awt.Color(0, 0, 0));

        btnIngresar.setBackground(new java.awt.Color(0, 102, 102));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLateralColorDerechoLayout = new javax.swing.GroupLayout(pnLateralColorDerecho);
        pnLateralColorDerecho.setLayout(pnLateralColorDerechoLayout);
        pnLateralColorDerechoLayout.setHorizontalGroup(
            pnLateralColorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLateralColorDerechoLayout.createSequentialGroup()
                .addGroup(pnLateralColorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLateralColorDerechoLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblTitulo))
                    .addGroup(pnLateralColorDerechoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(pnLateralColorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContrasenna)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pnLateralColorDerechoLayout.setVerticalGroup(
            pnLateralColorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLateralColorDerechoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTitulo)
                .addGap(70, 70, 70)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblContrasenna)
                .addGap(18, 18, 18)
                .addComponent(txtContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pnGeneral.add(pnLateralColorDerecho);
        pnLateralColorDerecho.setBounds(450, 0, 450, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        
        if(txtUsuario.getText().equals("admin") && txtContrasenna.getText().equals("1234")){
            GestionEmpleado frmGestionEmpleado = new GestionEmpleado();
            this.hide();
            frmGestionEmpleado.show();
        }else{
            JOptionPane.showMessageDialog(null, "Acceso Denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblContrasenna;
    private javax.swing.JLabel lblDeveloper;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnGeneral;
    private javax.swing.JPanel pnLateralColorDerecho;
    private javax.swing.JPanel pnLateralColorIzquierdo;
    private javax.swing.JPasswordField txtContrasenna;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
